# -*- coding: utf-8 -*-
"""Untitled0.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHHRhoPy5kB6pqVi_eNQ_yI-S71c6CI8
"""

import csv
import datetime


with open("menu.txt", "w") as file:
    file.write("* Lütfen Bir Pizza Tabanı Seçiniz:\n1: Klasik\n2: Margarita\n3: TürkPizza\n4: Sade Pizza\n* ve seçeceğiniz sos:\n11: Zeytin\n12: Mantarlar\n13: Keçi Peyniri\n14: Et\n15: Soğan\n16: Mısır\n* Teşekkür ederiz!")

# Pizza açıklama ve fiyatları
KLASIK_DESC = "Vazgeçilmez bir lezzet. Mozarella peyniri ve domates sosu ile ağzınıza layık..."
KLASIK_PRICE = 25

MARGHERITA_DESC = "Bir İtalyan mucizesi... Mozarella peyniri, domates sosu ve taze fesleğen yaprakları ile servis edilir."
MARGHERITA_PRICE = 30.0

TURK_DESC = "Ver mehteri... Sucuk, kaşar peyniri, domates ve biber ile..."
TURK_PRICE = 30.0

SADE_DESC = "Sadece domates sosu ile hazırlanan pizza."
SADE_PRICE = 20.0

# Sos açıklama ve fiyatları
OLIVE_DESC = "Zeytin Sosu"
OLIVE_PRICE = 2.0

MUSHROOM_DESC = "Mantar Sosu"
MUSHROOM_PRICE = 2.0

GOAT_CHEESE_DESC = "Keçi Peyniri Sosu"
GOAT_CHEESE_PRICE = 4.0

MEAT_DESC = "Et Sosu"
MEAT_PRICE = 5.0

ONION_DESC = "Soğan Sosu"
ONION_PRICE = 1.0

CORN_DESC = "Mısır Sosu"
CORN_PRICE = 2.0


class Pizza:
    def __init__(self, description, cost):
        self._description = description
        self._cost = cost
    
    def get_description(self):
        return self._description
    
    def get_cost(self):
        return self._cost


class ClassicPizza(Pizza):
    def __init__(self):
        super().__init__(KLASIK_DESC, KLASIK_PRICE)


class MargheritaPizza(Pizza):
    def __init__(self):
        super().__init__(MARGHERITA_DESC, MARGHERITA_PRICE)


class TurkishPizza(Pizza):
    def __init__(self):
        super().__init__(TURK_DESC, TURK_PRICE)


class SadePizza(Pizza): 
    def __init__(self):
        super().__init__(SADE_DESC, SADE_PRICE)



class Decorator(Pizza):
    def __init__(self, component):
        self._component = component
    
    def get_cost(self):
        return self._component.get_cost() + Pizza.get_cost(self)
    
    def get_description(self):
        return self._component.get_description() + ' ' + Pizza.get_description(self)


class Olive(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self._description = OLIVE_DESC
        self._cost = OLIVE_PRICE


class Mushroom(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self._description = MUSHROOM_DESC
        self._cost = MUSHROOM_PRICE


class GoatCheese(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self._description = GOAT_CHEESE_DESC
        self._cost = GOAT_CHEESE_PRICE


class Meat(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self._description = MEAT_DESC
        self._cost = MEAT_PRICE


class Onion(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self._description = ONION_DESC
        self._cost = ONION_PRICE


class Corn(Decorator):
    def __init__(self, component):
        super().__init__(component)
        self._description = CORN_DESC
        self._cost = CORN_PRICE

# Kullanıcının bilgilerini alıp veritabanına yazan fonksiyon
def save_order(name, id_number, credit_card_number, credit_card_pass, order_description, total_price):
    with open('Orders_Database.csv', mode='a', newline='') as file:
        writer = csv.writer(file)
        writer.writerow([name, id_number, credit_card_number, credit_card_pass, order_description, total_price])


def main():
    with open("menu.txt", "r") as file:
      menu = file.read()
      print(menu)
    pizza_choice = int(input("Lütfen bir pizza seçin: "))
    if pizza_choice == 1:
        pizza = ClassicPizza()
    elif pizza_choice == 2:
        pizza = MargheritaPizza()
    elif pizza_choice == 3:
        pizza = TurkishPizza()
    elif pizza_choice == 4:
        pizza = SadePizza()
    else:
        print("Geçersiz seçim.")
        return
    sauce_choice = int(input("Lütfen bir sos seçin: "))
    if sauce_choice == 11:
        sauce = Olive(pizza)
    elif sauce_choice == 12:
        sauce = Mushroom(pizza)
    elif sauce_choice == 13:
        sauce = GoatCheese(pizza)
    elif sauce_choice == 14:
        sauce = Meat(pizza)
    elif sauce_choice == 15:
        sauce = Onion(pizza)
    elif sauce_choice == 16:
        sauce = Corn(pizza)
    else:
        print("Geçersiz seçim.")
        return

    total_price = sauce.get_cost()

    name = input("İsim: ")
    tc_no = input("TC Kimlik No: ")
    credit_card_no = input("Kredi Kartı No: ")
    cc_pass = input("Şifre: ")

    save_order(name,tc_no,credit_card_no,cc_pass,sauce.get_description(),sauce.get_cost())
    print(sauce.get_description()+" siparişiniz toplam "+str(sauce.get_cost())+" ₺ tutmuştur. Afiyet olsun...")

main()
